// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.1
// source: auth/auth_service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_auth_service_proto protoreflect.FileDescriptor

const file_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x17auth/auth_service.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15auth/auth_model.proto2\xd7\x02\n" +
	"\x04Auth\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.google.protobuf.Empty\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x124\n" +
	"\aRefresh\x12\x14.auth.RefreshRequest\x1a\x13.auth.LoginResponse\x129\n" +
	"\bValidate\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponse\x126\n" +
	"\x06Logout\x12\x14.auth.RefreshRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\n" +
	"DeleteUser\x12\x13.auth.DeleteRequest\x1a\x16.google.protobuf.EmptyB3Z1github.com/GinciuuKitakaze/contracts/auth/go;authb\x06proto3"

var file_auth_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: auth.RegisterRequest
	(*LoginRequest)(nil),     // 1: auth.LoginRequest
	(*RefreshRequest)(nil),   // 2: auth.RefreshRequest
	(*ValidateRequest)(nil),  // 3: auth.ValidateRequest
	(*DeleteRequest)(nil),    // 4: auth.DeleteRequest
	(*emptypb.Empty)(nil),    // 5: google.protobuf.Empty
	(*LoginResponse)(nil),    // 6: auth.LoginResponse
	(*ValidateResponse)(nil), // 7: auth.ValidateResponse
}
var file_auth_auth_service_proto_depIdxs = []int32{
	0, // 0: auth.Auth.Register:input_type -> auth.RegisterRequest
	1, // 1: auth.Auth.Login:input_type -> auth.LoginRequest
	2, // 2: auth.Auth.Refresh:input_type -> auth.RefreshRequest
	3, // 3: auth.Auth.Validate:input_type -> auth.ValidateRequest
	2, // 4: auth.Auth.Logout:input_type -> auth.RefreshRequest
	4, // 5: auth.Auth.DeleteUser:input_type -> auth.DeleteRequest
	5, // 6: auth.Auth.Register:output_type -> google.protobuf.Empty
	6, // 7: auth.Auth.Login:output_type -> auth.LoginResponse
	6, // 8: auth.Auth.Refresh:output_type -> auth.LoginResponse
	7, // 9: auth.Auth.Validate:output_type -> auth.ValidateResponse
	5, // 10: auth.Auth.Logout:output_type -> google.protobuf.Empty
	5, // 11: auth.Auth.DeleteUser:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_service_proto_init() }
func file_auth_auth_service_proto_init() {
	if File_auth_auth_service_proto != nil {
		return
	}
	file_auth_auth_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_service_proto_rawDesc), len(file_auth_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_auth_service_proto_depIdxs,
	}.Build()
	File_auth_auth_service_proto = out.File
	file_auth_auth_service_proto_goTypes = nil
	file_auth_auth_service_proto_depIdxs = nil
}
